name: CI/CD Pipeline for FastAPI Application

on:
  push:
    branches:
      - main
      - develop

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set ENVIRONMENT variable
        run: |
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
            echo "DATABASE_URL=${{ secrets.STAGING_DATABASE_URL }}" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "DATABASE_URL=${{ secrets.PRODUCTION_DATABASE_URL }}" >> $GITHUB_ENV
          fi
      
      - name: Print environment variables for debugging
        run: |
          echo "ENVIRONMENT variable is set to $ENVIRONMENT"
          echo "DATABASE_URL is set to $DATABASE_URL"
      
      - name: Create mock tests/data directory
        run: mkdir -p tests/data && touch tests/data/dummy.txt
      
      - name: Run tests excluding tests/data/ directory
        run: pytest --ignore=tests/data/

  deploy:
    needs: setup-and-test  # Corrected to match the actual job name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Keep version consistent
      - name: Set up Python
        uses: actions/setup-python@v2  # Keep version consistent
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Authenticate with Google Cloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}  # Ensure this is set in your GitHub Secrets
          project_id: ${{ needs.setup-environment-variables.outputs.project_id }}  # Ensure this is set in your GitHub Secrets
      - name: Configure gcloud CLI
        run: gcloud config set project ${{ needs.setup-environment-variables.outputs.project_id}}
      - name: Deploy to Google App Engine
        run: gcloud app deploy app.yaml --quiet
      - name: Run Alembic migrations
        run: |
          if [ "$ENVIRONMENT" == "production" ]; then
            alembic upgrade head
          else
            echo "Skipping migrations for non-production environments."
        env:
          DATABASE_URL: $DATABASE_URL  # Use directly set variable

