name: CI/CD Pipeline for FastAPI Application

on:
  push:
    branches:
      - main
      - develop

jobs:
  setup-environment-variables:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
      database_url: ${{ steps.set-db-url.outputs.database_url }}
      gcp_sa_key: ${{ steps.set-gcp-key.outputs.gcp_sa_key }}
      project_id: ${{ steps.set-project-id.outputs.project_id }}
    steps:
      - id: set-env
        run: |
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "::set-output name=environment::staging"
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "::set-output name=environment::production"
          fi
      - id: set-db-url
        run: |
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "::set-output name=database_url::${{ secrets.STAGING_DATABASE_URL }}"
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "::set-output name=database_url::${{ secrets.PRODUCTION_DATABASE_URL }}"
          fi
      - id: set-gcp-key
        run: |
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "::set-output name=gcp_sa_key::${{ secrets.GCP_SA_KEY_STG }}"
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "::set-output name=gcp_sa_key::${{ secrets.GCP_SA_KEY_PROD }}"
          fi
      - id: set-project-id
        run: |
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "::set-output name=project_id::stage-413302"
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "::set-output name=project_id::micro-harmony-413302"
          fi

  test:
    needs: setup-environment-variables
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set DATABASE_URL for testing
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "DATABASE_URL=${{ secrets.STAGING_DATABASE_URL }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "DATABASE_URL=${{ secrets.PRODUCTION_DATABASE_URL }}" >> $GITHUB_ENV
          fi
          
        shell: bash
      - name: Print DATABASE_URL for debugging
        run: echo "DATABASE_URL is $DATABASE_URL"
      - name: Create mock tests/data directory
        run: |
          mkdir -p tests/data
          touch tests/data/dummy
      - name: Run tests excluding tests/data/ directory
        run: pytest --ignore=tests/data/


  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Authenticate with Google Cloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ needs.setup-environment-variables.outputs.gcp_sa_key }}
          project_id: ${{ needs.setup-environment-variables.outputs.project_id }}
      - name: Configure gcloud CLI
        run: gcloud config set project ${{ needs.setup-environment-variables.outputs.project_id }}
      - name: Deploy to Google App Engine
        run: gcloud app deploy app.yaml --quiet
      - name: Run Alembic migrations
        run: alembic upgrade head
        env:
          DATABASE_URL: ${{ needs.setup-environment-variables.outputs.database_url }}


