name: CI/CD Pipeline for FastAPI Application

on:
  push:
    branches:
      - main
      - develop

jobs:
  setup-environment-variables:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ github.ref == 'refs/heads/develop' && 'staging' || 'production' }}
      database_url: ${{ github.ref == 'refs/heads/develop' && secrets.STAGING_DATABASE_URL || secrets.PRODUCTION_DATABASE_URL }}
      gcp_sa_key: ${{ github.ref == 'refs/heads/develop' && secrets.GCP_SA_KEY_STG || secrets.GCP_SA_KEY_PROD }}
      project_id: ${{ github.ref == 'refs/heads/develop' && 'stage-413302' || 'micro-harmony-413302' }}

  test:
    needs: setup-environment-variables
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt
      - name: Print DATABASE_URL for debugging
        run: echo "DATABASE_URL is ${{ needs.setup-environment-variables.outputs.database_url }}"
      - name: Create mock tests/data directory
        run: mkdir -p tests/data && touch tests/data/dummy
      - name: Run tests excluding tests/data/ directory
        run: pytest --ignore=tests/data/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt
      - name: Authenticate with Google Cloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ needs.setup-environment-variables.outputs.gcp_sa_key }}
          project_id: ${{ needs.setup-environment-variables.outputs.project_id }}
      - name: Configure gcloud CLI
        run: gcloud config set project ${{ needs.setup-environment-variables.outputs.project_id }}
      - name: Deploy to Google App Engine
        run: gcloud app deploy app.yaml --quiet
      - name: Run Alembic migrations
        run: alembic upgrade head
        env:
          DATABASE_URL: ${{ needs.setup-environment-variables.outputs.database_url }}

